-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Empresa"
(
    "Rut" character varying(10),
    "Nombre" character varying(120),
    "Direccion" character varying(120),
    "Telefono" character varying(15),
    "Correo" character varying(80),
    "Web" character varying(50),
    PRIMARY KEY ("Rut")
);

CREATE TABLE IF NOT EXISTS public."Herramienta"
(
    "Id_Herramienta" numeric(12),
    "Nombre" character varying(120),
    "PrecioDia" numeric(12),
    PRIMARY KEY ("Id_Herramienta")
);

CREATE TABLE IF NOT EXISTS public."Arriendo"
(
    "Folio" numeric(12),
    "Fecha" date,
    "Dias" numeric(5),
    "Valor_Dia" numeric(12),
    "Garantía" character varying(30),
    "Herramienta_IdHerramienta" numeric(12),
    "Cliente_Rut" character varying(10),
    PRIMARY KEY ("Folio")
);

CREATE TABLE IF NOT EXISTS public."Cliente"
(
    "Rut" character varying(10) NOT NULL,
    "Nombre" character varying(120) NOT NULL,
    "Correo" character varying(80),
    "Direccion" character varying(120),
    "Celular" character varying(15),
    PRIMARY KEY ("Rut")
);

ALTER TABLE IF EXISTS public."Arriendo"
    ADD FOREIGN KEY ("Cliente_Rut")
    REFERENCES public."Cliente" ("Rut") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Arriendo"
    ADD FOREIGN KEY ("Herramienta_IdHerramienta")
    REFERENCES public."Herramienta" ("Id_Herramienta") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;