-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Empresa"
(
    "Rut" character varying(10) NOT NULL,
    "Nombre" character varying(120) NOT NULL,
    "Direccion" character varying(120),
    "Telefono" character varying(15),
    "Correo" character varying(80),
    "Web" character varying(50),
    PRIMARY KEY ("Rut")
);

CREATE TABLE IF NOT EXISTS public."Cliente"
(
    "Rut" character varying(10) NOT NULL,
    "Nombre" character varying(120) NOT NULL,
    "Correo" character varying(80),
    "Direccion" character varying(120),
    "Celular" character varying(15),
    "Alta" "char",
    PRIMARY KEY ("Rut")
);

CREATE TABLE IF NOT EXISTS public."Tipo_Vehiculo"
(
    "Id_Tipo_Vehículo" numeric(12) NOT NULL,
    "Nombre" character varying(120) NOT NULL,
    PRIMARY KEY ("Id_Tipo_Vehículo")
);

CREATE TABLE IF NOT EXISTS public."Venta"
(
    "Folio" numeric(12) NOT NULL,
    "Fecha" date,
    "Monto" numeric(12),
    "Vehículo_IdVehiculo" numeric(12),
    "Cliente_Rut" character varying(10),
    PRIMARY KEY ("Folio")
);

CREATE TABLE IF NOT EXISTS public."Vehículo"
(
    "Id_Vehículo" numeric(12) NOT NULL,
    "Patente" character varying(10),
    "Marca" character varying(20),
    "Modelo" character varying(20),
    "Color" character varying(15),
    "Precio" numeric(12),
    "Frecuencia_Mantencion" numeric(5),
    "Marca_IdMarca" numeric(12),
    "TipoVehículo_IdTipoVehículo" numeric(12),
    PRIMARY KEY ("Id_Vehículo")
);

CREATE TABLE IF NOT EXISTS public."Marca"
(
    "Id_Marca" numeric(12) NOT NULL,
    "Nombre" character varying(120),
    PRIMARY KEY ("Id_Marca")
);

CREATE TABLE IF NOT EXISTS public."Mantencion"
(
    "Id_Mantencion" numeric(12) NOT NULL,
    "Fecha" date,
    "Trabajos_Realizados" character varying(1000),
    "Venta_Folio" numeric(12),
    PRIMARY KEY ("Id_Mantencion")
);

ALTER TABLE IF EXISTS public."Venta"
    ADD FOREIGN KEY ("Cliente_Rut")
    REFERENCES public."Cliente" ("Rut") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Vehículo"
    ADD FOREIGN KEY ("TipoVehículo_IdTipoVehículo")
    REFERENCES public."Tipo_Vehiculo" ("Id_Tipo_Vehículo") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Vehículo"
    ADD FOREIGN KEY ("Marca_IdMarca")
    REFERENCES public."Marca" ("Id_Marca") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Vehículo"
    ADD FOREIGN KEY ("TipoVehículo_IdTipoVehículo")
    REFERENCES public."Venta" ("Vehículo_IdVehiculo") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Mantencion"
    ADD FOREIGN KEY ("Venta_Folio")
    REFERENCES public."Venta" ("Cliente_Rut") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;